name: ualet
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.0.4
  cached_network_image: 2.2.0+1
  http: ^0.12.1
  font_awesome_flutter: ^8.8.1
  flutter_datetime_picker: ^1.3.8
  rxdart: ^0.24.1
  flutter_bloc: ^4.0.0
  shared_preferences: ^0.5.7+3
  modal_progress_hud: ^0.1.3
  flutter_swiper: ^1.1.6
  percent_indicator: ^2.1.5
  sqflite:
  path:
  flutter_hooks: ^0.9.0
  fl_chart: ^0.11.1
  flutter_emoji: ^2.2.1+1
  flutter_masked_text: ^0.8.0
  dotted_border: ^1.0.5
  flutter_custom_clippers: ^1.1.1
  badges: ^1.1.1
  auto_route: ^0.5.0
  flushbar: ^1.10.4
  get_it: ^4.0.2
  injectable: ^1.0.4
  dio: ^3.0.9
  pin_code_text_field: ^1.6.0
  kt_dart: ^0.7.0
  dartz: ^0.9.1
  freezed_annotation: ^0.7.1
  freezed: ^0.9.2
  flutter_xlider: ^3.4.0
  email_validator: ^1.0.0
  bubble: ^1.1.9+1
  camera: 0.5.8+8
  path_provider:
  url_launcher: ^5.4.11
  firebase_core: ^0.5.0
  flutter_html: ^1.0.2
  pdf_render:
  video_player:
  chewie:
  file_picker: ^1.13.3
  flutter_typeahead: 1.8.8
  firebase_analytics: ^6.0.0
  appsflyer_sdk: ^6.2.3+1
  firebase_messaging: ^7.0.1
  webview_flutter: ^0.3.22+1
  autocomplete_textfield: ^1.7.3
  mime: ^0.9.7
  keyboard_actions: ^3.3.0+1
  get_ip: ^0.4.0
  geolocator: ^6.1.14
  flutter_webrtc: ^0.4.1
  analyzer: 0.39.14
  after_layout: ^1.0.7+2
  facebook_app_events: 0.11.2
  launch_review: ^2.0.0
  hexcolor: ^1.0.6
  sizer: ^1.1.8
  device_info:
  sentry_flutter: ^4.0.6
  huawei_push: 5.0.2+304

  tu_identidad:
    git:
      url: git://github.com/CRISTIANROJAS1995/tu_identidad.git
      ref: main



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
flutter_test:
  sdk: flutter
  auto_route_generator: ^0.5.0
  build_runner: 1.10.0
  injectable_generator: ^1.0.4
  package_info: ^0.4.1
  flutter_launcher_icons: "^0.8.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    # - assets/certs/
    - assets/fonts/
    - assets/images/
    - assets/docs/
    # - assets/vectors/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: ualet
      fonts:
        - asset: assets/fonts/alsschlangebold.otf

flutter_intl:
  enabled: true
  main_locale: es
