part of 'withdrawal_form_bloc.dart';

@freezed
abstract class WithdrawalFormState with _$WithdrawalFormState {
  const factory WithdrawalFormState({
    int withdrawalType,
    bool isNextProcess,
    ValidarTransactionPopupInfo popUpType,
    DashboardGoal goalChosen,
    BankInfo bankChosen,
    double totalwithdrawal,
    bool confirmedHolder,
    bool confirmedWithdrawal,
    int debitOptions,
    int goalOptions,
    bool showModalDeleteGoal,
    bool showModalReCalculateDebits,
    OTP otp,
    List<DashboardGoal> goalsChosen,
    List<double> ammountChosen,
    bool isSubmitting,
    bool isBelow,
    bool alreadyShown,
    Map<int, bool> alreadyChosen,
    DashboardGoal goalToAssign,
    DashboardGoal goalFromAssign,
    double valueAssigned,
    Option<Either<BaseFailure, bool>> phoneConfirmedOption,
    Option<Either<BaseFailure, bool>> withdrawalAllOption,
    Option<Either<BaseFailure, bool>> withdrawalParcialOption,
    Option<Either<BaseFailure, bool>> deleteGoalOption,
    Option<Either<BaseFailure, bool>> deleteDebitOption,
    Option<Either<BaseFailure, bool>> deleteAllGoalsOption,
    Option<Either<BaseFailure, bool>> deleteAllDebitsOption,
    bool checkbox,
    Option<Either<BaseFailure, bool>> assignMoneyOption,
    Option<Either<BaseFailure, SimulateTransactionRemoveMoney>> responseSimulation
  }) = _WithdrawalFormState;
  factory WithdrawalFormState.initial() => WithdrawalFormState(
        withdrawalType: 0,
        isNextProcess: false,
        popUpType: ValidarTransactionPopupInfo.empty(),
        goalChosen: DashboardGoal.empty(),
        bankChosen: BankInfo.empty(),
        goalsChosen: [
          DashboardGoal.empty(),
          DashboardGoal.empty(),
          DashboardGoal.empty(),
          DashboardGoal.empty(),
          DashboardGoal.empty(),
        ],
        alreadyChosen: {},
        ammountChosen: [0.0, 0.0, 0.0, 0.0, 0.0],
        isSubmitting: false,
        confirmedWithdrawal: false,
        phoneConfirmedOption: none(),
        totalwithdrawal: 0,
        otp: OTP(""),
        confirmedHolder: false,
        withdrawalAllOption: none(),
        withdrawalParcialOption: none(),
        debitOptions: 0,
        goalOptions: 0,
        showModalDeleteGoal: false,
        showModalReCalculateDebits: false,
        deleteAllDebitsOption: none(),
        deleteAllGoalsOption: none(),
        deleteDebitOption: none(),
        deleteGoalOption: none(),
        isBelow: false,
        alreadyShown: false,
        checkbox: false,
        goalFromAssign: DashboardGoal.empty(),
        goalToAssign: DashboardGoal.empty(),
        valueAssigned: 0.0,
        assignMoneyOption: none(),
        responseSimulation: none()
      );
}
